### ISSUE TITLE
Create min/max validators

### ISSUE THREAD

**Issue by kongeor** [jazorp/jazorp#3]
We need to create validators for min and max values. Clients should provide deltas for floating point numbers.

**Comment by basalt79** [comment]
so you need to enrich the validation to verify Doubles to be greater or less then provided Double?

**Comment by kongeor** [comment]
We will have to add a `min` and `max` and probably a combo of these two to the `Validators` class. You may provide a `java.lang.Number` to cover all cases but it may be a bit messy to handle the floating point cases. 

Regarding the comparison check the way `junit` does them: https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/Assert.java#L603

@basalt79
