### ISSUE TITLE
Fix spark java logger

### ISSUE THREAD

**Issue by kongeor** [jazorp/jazorp#6]
Unfortunately spark's logger is not working in the 'spark-simple' example (in the examples branch). It would be nice to have some additional logging when the request is processed.

**Comment by mclay** [comment]
Hey, I would like to work on this.
Can you please explain briefly what kind of logging you expect?
@kongeor

**Comment by kongeor** [comment]
Hey, there is a missing logger dependency I think, so there are no logs at all. Check [this](http://sparkjava.com/documentation#examples-and-faq). We just want the enabled and probably a couple of them for the valid/invalid cases - nothing really fancy. @mclay
